import { type Readable } from "node:stream"
import { type FileKind, type FileRef, type StorageUsage } from "@alg/shared"

export interface PutInput {
  workspaceId: string
  kind: FileKind
  /** Extension without the dot. Generated by the caller, never taken from a request. */
  ext: string
  data: Buffer | Readable
  /** Overrides the extension-derived MIME type. */
  mime?: string
  /** Absolute expiry. Defaults to the per-kind retention window. */
  expiresAt?: Date | null
}

/**
 * Narrow storage seam. One implementation today (LocalFileStorage writing to a
 * mounted volume); the interface exists so swapping in object storage later does
 * not touch call sites.
 */
export interface FileStorage {
  put(input: PutInput): Promise<FileRef>
  get(id: string): Promise<Readable>
  stat(id: string): Promise<{ size: number; mime: string; createdAt: Date }>
  delete(id: string): Promise<void>
  /** Backs the storage section of GET /v1/health. */
  usage(): Promise<StorageUsage>
}

export class FileNotFoundError extends Error {
  constructor(id: string) {
    super(`File ${id} not found`)
    this.name = "FileNotFoundError"
  }
}

export class StorageLimitExceededError extends Error {
  constructor(usedBytes: number, maxBytes: number) {
    super(`Storage soft limit exceeded: ${usedBytes} of ${maxBytes} bytes used`)
    this.name = "StorageLimitExceededError"
  }
}
