import { isAbsolute, normalize, resolve, sep } from "node:path"
import { FILE_KINDS, type FileKind } from "@alg/shared"

/**
 * Path construction for the local file store.
 *
 * The rule this module exists to enforce: a storage path is NEVER assembled from
 * request input. Every component is either a validated uuid, a member of a closed
 * enum, or generated here. buildRelativePath() therefore rejects anything that is
 * not exactly those shapes rather than trying to sanitize hostile input.
 */

export class UnsafePathError extends Error {
  constructor(reason: string) {
    super(`Refusing to build storage path: ${reason}`)
    this.name = "UnsafePathError"
  }
}

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i
/** Extensions are generated by us, never echoed from a request. */
const EXT_RE = /^[a-z0-9]{1,8}$/

function assertUuid(value: string, label: string): void {
  if (typeof value !== "string" || !UUID_RE.test(value)) {
    throw new UnsafePathError(`${label} is not a uuid`)
  }
}

function assertNoNullBytes(value: string, label: string): void {
  if (value.includes("\0")) {
    throw new UnsafePathError(`${label} contains a null byte`)
  }
}

export interface BuildPathInput {
  workspaceId: string
  kind: FileKind
  fileId: string
  ext: string
  /** Defaults to now; injectable so tests are deterministic. */
  at?: Date
}

/**
 * Produces `{workspace_id}/{kind}/{yyyy}/{mm}/{file_id}.{ext}`.
 * Throws on anything that is not a uuid / known kind / plain extension.
 */
export function buildRelativePath(input: BuildPathInput): string {
  const { workspaceId, kind, fileId, ext, at = new Date() } = input

  assertNoNullBytes(workspaceId, "workspaceId")
  assertNoNullBytes(fileId, "fileId")
  assertNoNullBytes(ext, "ext")

  assertUuid(workspaceId, "workspaceId")
  assertUuid(fileId, "fileId")

  if (!FILE_KINDS.includes(kind)) {
    throw new UnsafePathError(`unknown file kind "${String(kind)}"`)
  }

  const normalizedExt = ext.toLowerCase().replace(/^\./, "")
  if (!EXT_RE.test(normalizedExt)) {
    throw new UnsafePathError(`extension "${ext}" is not alphanumeric`)
  }

  const year = String(at.getUTCFullYear()).padStart(4, "0")
  const month = String(at.getUTCMonth() + 1).padStart(2, "0")

  return `${workspaceId}/${kind}/${year}/${month}/${fileId}.${normalizedExt}`
}

/**
 * Resolves a stored relative path against the storage root and verifies the result
 * stays inside it. Defence in depth: even a corrupted DB row cannot escape the root.
 */
export function resolveWithinRoot(root: string, relativePath: string): string {
  assertNoNullBytes(relativePath, "relativePath")

  if (isAbsolute(relativePath)) {
    throw new UnsafePathError("relative path must not be absolute")
  }
  // Reject Windows-style drive letters and UNC prefixes explicitly - isAbsolute()
  // does not treat "C:\..." as absolute when running on POSIX.
  if (/^[a-zA-Z]:/.test(relativePath) || relativePath.startsWith("\\\\")) {
    throw new UnsafePathError("relative path must not contain a drive or UNC prefix")
  }

  const normalized = normalize(relativePath)
  if (
    normalized === ".." ||
    normalized.startsWith(`..${sep}`) ||
    normalized.includes(`${sep}..${sep}`)
  ) {
    throw new UnsafePathError("relative path escapes the storage root")
  }

  const rootResolved = resolve(root)
  const target = resolve(rootResolved, normalized)

  if (target !== rootResolved && !target.startsWith(rootResolved + sep)) {
    throw new UnsafePathError("resolved path escapes the storage root")
  }

  return target
}

/** Default MIME types for the extensions we generate. */
export const MIME_BY_EXT: Record<string, string> = {
  png: "image/png",
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  webp: "image/webp",
  pdf: "application/pdf",
  csv: "text/csv",
  json: "application/json",
  html: "text/html",
  txt: "text/plain",
  gz: "application/gzip",
}

export function mimeForExt(ext: string): string {
  return MIME_BY_EXT[ext.toLowerCase().replace(/^\./, "")] ?? "application/octet-stream"
}
